---
title: "IndividualAaron"
author: "Aaron Hanrahan"
date: "4/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, error=FALSE, message=FALSE, warning=FALSE}
# Import data.
casesByAge <- readr::read_csv('cases_by_age_group.csv')
deathsByAge <- readr::read_csv('deaths_by_age_group.csv')
covid19Data <- readr::read_csv('covid19_vaccinations_in_the_united_states.csv')
```

```{r, error=FALSE, message=FALSE, warning=FALSE}
# Packages
library(lubridate)
library(dplyr)
library(tidyverse)
library(ggthemes)
```

```{r, echo = FALSE}
covid19Data <- covid19Data %>%
  rename(
    State = `State/Territory/Federal Entity`,
    total.Doses = `Total Doses Delivered`,
    doses.Per.100K = `Doses Delivered per 100K`,
    doses.Per.100K.18plus = `18+ Doses Delivered per 100K`,
    total.Doses.Administered = `Total Doses Administered by State where Administered`,
    doses.Administered.Per.100k = `Doses Administered per 100k by State where Administered`,
    doses.Administered.18plus = `18+ Doses Administered by State where Administered`,
    doses.Administered.18plus.Per.100k = `18+ Doses Administered per 100K by State where Administered`,
    people.at.Least.One.Dose = `People with at least One Dose by State of Residence`,
    percent.at.Least.One.Dose = `Percent of Total Pop with at least One Dose by State of Residence`,
    people.at.Least.One.Dose.18plus = `People 18+ with at least One Dose by State of Residence`,
    percent.at.Least.One.Dose.18plus = `Percent of 18+ Pop with at least One Dose by State of Residence`,
    people.Fully.Vaccinated = `People Fully Vaccinated by State of Residence`,
    percent.Fully.Vaccinated = `Percent of Total Pop Fully Vaccinated by State of Residence`,
    people.Fully.Vaccinated.18plus = `People 18+ Fully Vaccinated by State of Residence`,
    percent.Fully.Vaccinated.18plus = `Percent of 18+ Pop Fully Vaccinated by State of Residence`,
    doses.Delivered.Pfizer = `Total Number of Pfizer doses delivered`,
    doses.Delivered.Moderna = `Total Number of Moderna doses delivered`,
    doses.Delivered.Janssen = `Total Number of Janssen doses delivered`,
    doses.Delivered.Unknown = `Total Number of doses from unknown manufacturer delivered`,
    doses.Administered.Janssen = `Total Number of Janssen doses administered`,
    doses.Administered.Moderna = `Total Number of Moderna doses administered`,
    doses.Administered.Pfizer = `Total Number of Pfizer doses adminstered`,
    doses.Administered.Unknown = `Total Number of doses from unknown manufacturer administered`,
    people.Fully.Vaccinated.Moderna = `People Fully Vaccinated Moderna Resident`,
    people.Fully.Vaccinated.Pfizer = `People Fully Vaccinated Pfizer Resident`,
    people.Fully.Vaccinated.Janssen = `People Fully Vaccinated Janssen Resident`,
    people.Fully.Vaccinated.Unknown = `People Fully Vaccinated Unknown 2-dose manufacturer Resident`,
    people.Fully.Vaccinated.Moderna.18plus = `People 18+ Fully Vaccinated Moderna Resident`,
    people.Fully.Vaccinated.Pfizer.18plus = `People 18+ Fully Vaccinated Pfizer Resident`,
    people.Fully.Vaccinated.Janssen.18plus = `People 18+ Fully Vaccinated Janssen Resident`,
    people.Fully.Vaccinated.Unknown.18plus = `People 18+ Fully Vaccinated Unknown 2-dose manufacturer Resident`,
    people.Two.Doses = `People with 2 Doses by State of Residence`,
    percent.1plus.Doses = `Percent of Total Pop with 1+ Doses by State of Residence`,
    Oneplus.Doses.18plus = `People 18+ with 1+ Doses by State of Residence`,
    percent.1plus.Doses.18plus = `Percent of 18+ Pop with 1+ Doses by State of Residence`,
    percent.2Doses = `Percent of Total Pop with 2 Doses by State of Residence`,
    people.18plus.2Doses = `People 18+ with 2 Doses by State of Residence`,
    percent.18plus.2Doses = `Percent of 18+ Pop with 2 Doses by State of Residence`,
    people.1plus.Doses = `People with 1+ Doses by State of Residence`,
    people.1plus.Doses.65plus = `People 65+ with at least One Dose by State of Residence`,
    percent.1plus.Doses.65plus = `Percent of 65+ Pop with at least One Dose by State of Residence`,
    people.Fully.Vaccinated.65plus = `People 65+ Fully Vaccinated by State of Residence`,
    percent.Fully.Vaccinated.65plus = `Percent of 65+ Pop Fully Vaccinated by State of Residence`,
    people.Fully.Vaccinated.Moderna.65plus = `People 65+ Fully Vaccinated_Moderna_Resident`,
    people.Fully.Vaccinated.Pfizer.65plus = `People 65+ Fully Vaccinated_Pfizer_Resident`,
    people.Fully.Vaccinated.Janssen.65plus = `People 65+ Fully Vaccinated_Janssen_Resident`,
    people.Fully.Vaccinated.Unknown.65plus = `People 65+ Fully Vaccinated_Unknown 2-dose Manuf_Resident`,
    doses.Administered.65plus = `65+ Doses Administered by State where Administered`,
    doses.Administered.Per.100K.65plus = `Doses Administered per 100k of 65+ pop by State where Administered`,
    doses.Delivered.Per.100K.65plus = `Doses Delivered per 100k of 65+ pop`
  )
```

```{r, error=FALSE, message=FALSE, warning=FALSE, echo = FALSE}
covid19Data$doses.Per.100K <- as.numeric(covid19Data$doses.Per.100K)
covid19Data$doses.Per.100K.18plus <- as.numeric(covid19Data$doses.Per.100K.18plus)
covid19Data$doses.Administered.Per.100k <- as.numeric(covid19Data$doses.Administered.Per.100k)
covid19Data$doses.Administered.18plus.Per.100k <- as.numeric(covid19Data$doses.Administered.18plus.Per.100k)
covid19Data$percent.at.Least.One.Dose <- as.numeric(covid19Data$percent.at.Least.One.Dose)
covid19Data$percent.at.Least.One.Dose.18plus <- as.numeric(covid19Data$percent.at.Least.One.Dose.18plus)
covid19Data$percent.Fully.Vaccinated <- as.numeric(covid19Data$percent.Fully.Vaccinated)
covid19Data$percent.Fully.Vaccinated.18plus <- as.numeric(covid19Data$percent.Fully.Vaccinated.18plus)
covid19Data$percent.1plus.Doses <- as.numeric(covid19Data$percent.1plus.Doses)
covid19Data$percent.1plus.Doses.18plus <- as.numeric(covid19Data$percent.1plus.Doses.18plus)
```

```{r}
# Which vaccine is most popular across the different states?

nonContiguous <- c("American Samoa", "Bureau of Prisons", "Dept of Defense", "Federated States of Micronesia", "Indian Health Svc", "Marshall Islands", "Northern Mariana Islands", "Puerto Rico", "Republic of Palau", "Veterans Health", "Virgin Islands", "Guam", "Alaska", "Hawaii")

popular <- covid19Data %>%
  select(State, people.Fully.Vaccinated.Pfizer, people.Fully.Vaccinated.Moderna, people.Fully.Vaccinated.Janssen, 
  people.Fully.Vaccinated.Unknown) %>%
  rename(
    moderna = people.Fully.Vaccinated.Moderna,
    pfizer = people.Fully.Vaccinated.Pfizer,
    janssen = people.Fully.Vaccinated.Janssen,
    unknown = people.Fully.Vaccinated.Unknown
  ) %>%
  pivot_longer(!State, names_to = "vaccineName", values_to = "numFullyVac") %>%
  filter(!(State %in% nonContiguous))

```

```{r}
popularEachState <- popular %>%
  group_by(State) %>%
  top_n(1, numFullyVac)

popularEachState$State <- tolower(popularEachState$State)

state <- map_data("state")

popEachStateMap <- popularEachState %>%
  left_join(state, by = c("State" = "region"))
```

```{r}
p <- popEachStateMap %>%
  ggplot(aes(x = long, y = lat, fill = vaccineName)) + geom_polygon(aes(group=group), color = "white") +
  theme_map() + ggtitle("Which Vaccine are More People Fully Vaccinated With Per State?")

p + scale_fill_manual(name = "Vaccine Name", values = c("#D23369", "#2A3990"), labels = c("Moderna", 
  "Pfizer"))
```

```{r}
# Which vaccine is getting administered the most across the different states?

administered <- covid19Data %>%
  select(State, doses.Administered.Moderna, doses.Administered.Janssen, doses.Administered.Pfizer,
  doses.Administered.Unknown) %>%
  rename(
    moderna = doses.Administered.Moderna,
    pfizer = doses.Administered.Pfizer,
    janssen = doses.Administered.Janssen,
    unknown = doses.Administered.Unknown
  ) %>%
  pivot_longer(!State, names_to = "vaccineName", values_to = "administeredCount") %>%
  filter(!(State %in% nonContiguous))

adminEachState <- administered %>%
  group_by(State) %>%
  top_n(1, administeredCount)
  
adminEachState$State <- tolower(adminEachState$State)

adminEachStateMap <- adminEachState %>%
  left_join(state, by = c("State" = "region"))
```

```{r}
q <- adminEachStateMap %>%
  ggplot(aes(x = long, y = lat, fill = vaccineName)) + geom_polygon(aes(group=group), color = "white") +
  theme_map() + ggtitle("Which Vaccine are More People Administered Per State?")

q + scale_fill_manual(name = "Vaccine Name", values = c("#D23369", "#2A3990"), labels = c("Moderna", 
  "Pfizer"))
```

```{r}
# Comparing 1st Dose Administration between Ages 65 and up, and ages 65 and under

# Iowa, Illinois, Kansas, Minnesota, Missouri, Nebraska, South Dakota, Wisconsin
populations <- c(3155000, 12670000, 2913000, 5640000, 6137000, 1934000, 884659, 5822000)
populations65andup <- c(552125, 2039870, 474819, 919320, 919320, 315242, 152161, 1018850)
populations65andunder <- populations - populations65andup

onePlusDoses <- covid19Data %>%
  select(State, people.1plus.Doses, people.1plus.Doses.65plus) %>%
  rename(
    plusNormal = people.1plus.Doses,
    plus65 = people.1plus.Doses.65plus
  ) %>%
  mutate(plus65under = plusNormal - plus65) %>%
  filter(!(State %in% nonContiguous)) %>%
  select(-plusNormal) %>% 
  filter(State %in% c("Iowa", "South Dakota", "Minnesota", "Illinois", "Wisconsin", "Missouri", "Nebraska", "Kansas"))

onePlusDoses$State <- tolower(onePlusDoses$State)
onePlusDoses$PopulationUp = populations65andup
onePlusDoses$PopulationUnder = populations65andunder


onePlusDoses <- onePlusDoses %>%
  mutate(plus65percent = ((plus65 / PopulationUp) * 100), plus65Upercent = ((plus65under / PopulationUnder) * 100))

nearIowa <- state %>%
  filter(region %in% c("iowa", "south dakota", "minnesota", "illinois", "wisconsin", "missouri", "nebraska", "kansas"))

onePlusMap <- onePlusDoses %>%
  left_join(nearIowa, by = c("State" = "region"))
```

```{r}
s <- onePlusMap %>%
  ggplot(aes(x = long, y = lat, fill = plus65Upercent)) + geom_polygon(aes(group=group), color = "black")

s + theme_map() + coord_map() + scale_fill_gradient2(low = "#2A3990", high = "#D23369", mid = "white", midpoint = 22.5, limits = c(15, 30), name = "Percent of Under 65 Population") + theme(legend.position="right") + ggtitle("Per State 1st Dose Administered to ages Under 65")
```

```{r}
s2 <- onePlusMap %>%
  ggplot(aes(x = long, y = lat, fill = plus65percent)) + geom_polygon(aes(group=group), color = "black")

s2 + theme_map() + coord_map() + scale_fill_gradient2(low = "#2A3990", high = "#D23369", mid = "white", midpoint = 80, limits = c(75, 85), name = "Percent of 65+ Population") + theme(legend.position="right") + ggtitle("Per State 1st Dose Administered to ages 65 and Over")
```

```{r}
# Sum of fully vaccinated and administered across all U.S.

administeredTotal <- administered %>%
  select(-State) %>%
  group_by(vaccineName) %>%
  summarize(administeredCount = sum(administeredCount)) %>%
  mutate(administeredCount = (administeredCount / sum(administeredCount)) * 100)
  
popularTotal <- popular %>%
  select(-State) %>%
  group_by(vaccineName) %>%
  summarize(numFullyVac = sum(numFullyVac)) %>%
  mutate(numFullyVac = (numFullyVac / sum(numFullyVac)) * 100)

totalData <- administeredTotal %>%
  left_join(popularTotal, by = "vaccineName") %>%
  rename(
    administered = administeredCount,
    fullyVaccinated = numFullyVac
  ) %>%
  pivot_longer(!vaccineName, names_to = "type", values_to = "values")
```

```{r}
q <- totalData %>% 
  ggplot(aes(x = vaccineName, weight = values, fill = type)) + geom_bar(position = 'dodge') + geom_text(aes(label =
  round(values, digits = 2)), stat = "count", colour = "white", position = position_dodge(.9), vjust = 1)

q + scale_fill_manual(name = "Distribution Type", values = c("#D23369", "#2A3990"), labels = c("Administered", 
  "Fully Vaccinated")) + ylab("Percentage") + xlab("Vaccine Company") + scale_x_discrete(labels = c("Johnson & Johnson", 
  "Moderna", "Pfizer", "Unknown")) + ggtitle("Vaccine Percentage Comparison Between Administered and Fully Vaccinated")
```





























