---
title: "Team"
author: "Shellie Jurchisin, Aaron Hanrahan, Madeline Egbert, Ritvik Maripally, Nick Cory"
date: "4/19/2021"
output: html_document
---
```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, error=FALSE, message=FALSE, warning=FALSE}
# Import data.
casesByAge <- readr::read_csv('cases_by_age_group.csv')
deathsByAge <- readr::read_csv('deaths_by_age_group.csv')
covid19Data <- readr::read_csv('covid19_vaccinations_in_the_united_states.csv')
```

```{r}
covid19Data <- covid19Data %>%
  rename(
    State = `State/Territory/Federal Entity`,
    total.Doses = `Total Doses Delivered`,
    doses.Per.100K = `Doses Delivered per 100K`,
    doses.Per.100K.18plus = `18+ Doses Delivered per 100K`,
    total.Doses.Administered = `Total Doses Administered by State where Administered`,
    doses.Administered.Per.100k = `Doses Administered per 100k by State where Administered`,
    doses.Administered.18plus = `18+ Doses Administered by State where Administered`,
    doses.Administered.18plus.Per.100k = `18+ Doses Administered per 100K by State where Administered`,
    people.at.Least.One.Dose = `People with at least One Dose by State of Residence`,
    percent.at.Least.One.Dose = `Percent of Total Pop with at least One Dose by State of Residence`,
    people.at.Least.One.Dose.18plus = `People 18+ with at least One Dose by State of Residence`,
    percent.at.Least.One.Dose.18plus = `Percent of 18+ Pop with at least One Dose by State of Residence`,
    people.Fully.Vaccinated = `People Fully Vaccinated by State of Residence`,
    percent.Fully.Vaccinated = `Percent of Total Pop Fully Vaccinated by State of Residence`,
    people.Fully.Vaccinated.18plus = `People 18+ Fully Vaccinated by State of Residence`,
    percent.Fully.Vaccinated.18plus = `Percent of 18+ Pop Fully Vaccinated by State of Residence`,
    doses.Delivered.Pfizer = `Total Number of Pfizer doses delivered`,
    doses.Delivered.Moderna = `Total Number of Moderna doses delivered`,
    doses.Delivered.Janssen = `Total Number of Janssen doses delivered`,
    doses.Delivered.Unknown = `Total Number of doses from unknown manufacturer delivered`,
    doses.Administered.Janssen = `Total Number of Janssen doses administered`,
    doses.Administered.Moderna = `Total Number of Moderna doses administered`,
    doses.Administered.Pfizer = `Total Number of Pfizer doses adminstered`,
    doses.Administered.Unknown = `Total Number of doses from unknown manufacturer administered`,
    people.Fully.Vaccinated.Moderna = `People Fully Vaccinated Moderna Resident`,
    people.Fully.Vaccinated.Pfizer = `People Fully Vaccinated Pfizer Resident`,
    people.Fully.Vaccinated.Janssen = `People Fully Vaccinated Janssen Resident`,
    people.Fully.Vaccinated.Unknown = `People Fully Vaccinated Unknown 2-dose manufacturer Resident`,
    people.Fully.Vaccinated.Moderna.18plus = `People 18+ Fully Vaccinated Moderna Resident`,
    people.Fully.Vaccinated.Pfizer.18plus = `People 18+ Fully Vaccinated Pfizer Resident`,
    people.Fully.Vaccinated.Janssen.18plus = `People 18+ Fully Vaccinated Janssen Resident`,
    people.Fully.Vaccinated.Unknown.18plus = `People 18+ Fully Vaccinated Unknown 2-dose manufacturer Resident`,
    people.Two.Doses = `People with 2 Doses by State of Residence`,
    percent.1plus.Doses = `Percent of Total Pop with 1+ Doses by State of Residence`,
    Oneplus.Doses.18plus = `People 18+ with 1+ Doses by State of Residence`,
    percent.1plus.Doses.18plus = `Percent of 18+ Pop with 1+ Doses by State of Residence`,
    percent.2Doses = `Percent of Total Pop with 2 Doses by State of Residence`,
    people.18plus.2Doses = `People 18+ with 2 Doses by State of Residence`,
    percent.18plus.2Doses = `Percent of 18+ Pop with 2 Doses by State of Residence`,
    people.1plus.Doses = `People with 1+ Doses by State of Residence`,
    people.1plus.Doses.65plus = `People 65+ with at least One Dose by State of Residence`,
    percent.1plus.Doses.65plus = `Percent of 65+ Pop with at least One Dose by State of Residence`,
    people.Fully.Vaccinated.65plus = `People 65+ Fully Vaccinated by State of Residence`,
    percent.Fully.Vaccinated.65plus = `Percent of 65+ Pop Fully Vaccinated by State of Residence`,
    people.Fully.Vaccinated.Moderna.65plus = `People 65+ Fully Vaccinated_Moderna_Resident`,
    people.Fully.Vaccinated.Pfizer.65plus = `People 65+ Fully Vaccinated_Pfizer_Resident`,
    people.Fully.Vaccinated.Janssen.65plus = `People 65+ Fully Vaccinated_Janssen_Resident`,
    people.Fully.Vaccinated.Unknown.65plus = `People 65+ Fully Vaccinated_Unknown 2-dose Manuf_Resident`,
    doses.Administered.65plus = `65+ Doses Administered by State where Administered`,
    doses.Administered.Per.100K.65plus = `Doses Administered per 100k of 65+ pop by State where Administered`,
    doses.Delivered.Per.100K.65plus = `Doses Delivered per 100k of 65+ pop`
  )
```

```{r}
covid19Data$doses.Per.100K <- as.numeric(covid19Data$doses.Per.100K)
covid19Data$doses.Per.100K.18plus <- as.numeric(covid19Data$doses.Per.100K.18plus)
covid19Data$doses.Administered.Per.100k <- as.numeric(covid19Data$doses.Administered.Per.100k)
covid19Data$doses.Administered.18plus.Per.100k <- as.numeric(covid19Data$doses.Administered.18plus.Per.100k)
covid19Data$percent.at.Least.One.Dose <- as.numeric(covid19Data$percent.at.Least.One.Dose)
covid19Data$percent.at.Least.One.Dose.18plus <- as.numeric(covid19Data$percent.at.Least.One.Dose.18plus)
covid19Data$percent.Fully.Vaccinated <- as.numeric(covid19Data$percent.Fully.Vaccinated)
covid19Data$percent.Fully.Vaccinated.18plus <- as.numeric(covid19Data$percent.Fully.Vaccinated.18plus)
covid19Data$percent.1plus.Doses <- as.numeric(covid19Data$percent.1plus.Doses)
covid19Data$percent.1plus.Doses.18plus <- as.numeric(covid19Data$percent.1plus.Doses.18plus)
```

```{r}
dosesAdministered <- covid19Data %>%
  select(State, doses.Administered.Moderna, doses.Administered.Janssen, doses.Administered.Pfizer,
  doses.Administered.Unknown) %>%
  rename(
    moderna = doses.Administered.Moderna,
    pfizer = doses.Administered.Pfizer,
    janssen = doses.Administered.Janssen,
    unknown = doses.Administered.Unknown
  ) %>%
  pivot_longer(!State, names_to = "vaccineName", values_to = "administeredCount")
  
str(dosesAdministered)
```
